<div class="follow-us container-fluid" align="centered">
  <h1> FOLLOW US</h1>
  <div class="social row">
    <div class="col-md-2">
      <h6 class="insta">INSTAGRAM</h6>
    </div>
    <div class="col-md-2">
      <h6 class="fb">FACEBOOK</h6>
    </div>
    <div class="col-md-2">
      <h6 class="tw">TWITTER</h6>
    </div>
    <div class="col-md-2">
      <h6 class="google">GOOGLE PLUS</h6>
    </div>
    <div class="col-md-2">
      <h6 class="pint">PINTEREST</h6>
    </div>
  </div>
  <div class="follow-us-cta">
    <input type="button" value="Read More">
  </div>
</div>