<div id="hero">
  <div class="hero-wrapper">
    <div class="title-wrapper">
      <div class="title">
        <h1>Reach your bodybuilding goals!</h1>
      </div>
    </div>
    <div class="paragraph-wrapper">
      <div class="paragraph">
        <p>Bodybuilding takes a lot of hard work and dedication</p>
      </div>
    </div>
    <div class="cta-wrapper">
      <div class="cta" align="center">
        <input type="button" name="read-more" value="Read More">
      </div>
    </div>
  </div>
</div>
