<div id="welcome-block">
  <div class="welcome-block-wrapper">
    
    <div class="title-wrapper">
      <div class="title" align="center">
        <h1>Welcome</h1>
        <hr>
      </div>
    </div>
    
    <div class="cols-wrapper">
      <div class="container-fluid" >
        
        <div class="row">
          
          <div class="column col-xs-12 col-sm-4 ">
              <p>This website is for those who want to look great and feel great. Anyone can be healthier, have more energy, sleep better, and feel better about themselves through bodybuilding. Bodybuilding doesn't have to be expensive or take a lot of time. Our focus here is on workouts the natural bodybuilder can do at home with inexpensive equipment.
              </p>
          </div>
          
          <div class="col-xs-12 col-sm-4 column">
            <div class="paragraph-wrapper">
              <p>Don't be fooled, home workouts do not mean easy workouts and they can be just as effective as the gym. We include basic training tips for the beginner and plateau busting techniques for the hard-gainer bodybuilder. We make extensive use of videos and photos to illustrate how to do the exercises.
              </p>
            </div>
          </div>
          
          <div class="col-xs-12 col-sm-4 column">
            <div class="paragraph-wrapper">
              <p>We don't encourage the use of any supplements or the purchase of any new equipment, you can build a fantastic physique with just a cheap used set of dumbbells. 100% unique bodybuilding workout programs that you won't find anywhere else on the web.
              </p>
            </div>
          </div>
          
        </div>
        
      </div>
    </div>
    
    <div class="cta-wrapper">
      <div class="cta" align="center">
        <input type="button" name="read-more" value="Read More">
      </div>
    </div>
    
  </div>
</div>