<div id="womens">
  <div class="container-fluid">
    <div class="row">
      <div class="title-wrapper col-xs-12 col-sm-5 col-sm-offset-1 col-md-6">
        <div class="title">
          <h1>Women's area</h1>
          <hr align="left">
        </div>
      </div>

      <div class="subtitle-wrapper col-xs-12 col-sm-5 col-sm-offset-1 col-md-6">
        <div class="subtitle">
          <h4>The female component of competitive bodybuilding</h4>
        </div>
      </div>

      <div class="paragraph-wrapper col-xs-12 col-sm-7 col-sm-offset-1 col-md-6">
        <div class="paragraph">
          <p>
            Female bodybuilding originally developed as an outgrowth of not only the late nineteenth-century European vaudeville and circus strongwomen acts, Bernarr Macfadden's turn of the century women's physique competitions, and the weightlifting of Abbye "Pudgy" Stockton, but also as an outgrowth of the men's bodybuilding. The contest formats of men's events during the 1950s to the mid-1970s had often been supplemented with either a women's beauty contest or bikini show.
          </p>
        </div>
      </div>

      <div class="cta-wrapper col-xs-12 col-sm-6 col-sm-offset-1 ">
        <div class="cta">
          <input type="button" name="read-more" value="Read More">
        </div>
      </div>
    </div>
  </div>
</div>
