<div class="exercises container-fluid">
  <div class="row">
    <div class="none col-md-6">
    </div>
    <div class="text col-md-6">
      <h1>EXERCISES</h1>
      <h4>Find out how to build incredible muscle mass fast</h4>
      <p>In competitive bodybuilding, bodybuilders aspire to develop and maintain an aesthetically pleasing body and balanced physique. In prejudging, competitors do a series of mandatory poses – the front lat spread, the rear lat spread, the front double biceps, the back double biceps, the side chest, the side triceps, the Most Muscular (men only), and the thigh-abdominal pose. Each competitor also performs a routine to display the physique.</p>
      <div class="exercises-cta">
      <input type="button" value="Read More">
      </div>
    </div>
  </div>
</div>