<div id="header">
  <button id="menu-button"><i class="fas fa-bars"></i> HOME</button>
  <div class="logo-wrapper">
      <img src="img/logo.png" class="logo ">
  </div>
  <nav id="my-menu">
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a>
         <ul class="Vertical">
            <li><a href="#">What we offer</a></li>
              <li><dir><a href="#">Bodybuilding exercises</a></dir></li>
              <li><dir><a href="#">Bodybuilding nutrition</a></dir></li>
              <li><dir><a href="#">Training packages</a></dir></li>
              <li><dir><a href="#">Gym equipment</a></dir></li>
            <li><a href="#">Benefits</a></li>
            <li><a href="#">Our programs</a></li>
            <li><a href="#">Testimonials</a></li>
         </ul>
      </li>
      <li><a href="#">Services</a></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Gallery</a></li>
      <li><a href="#">Contacts</a></li>
    </ul>
  </nav>
</div>
