<div id="header-mobile" class="Fixed">
  <a href="#" id="menu-button">HOME</a>
  <p><?php print $title;?></p>
</div>

<div id="header">
  <div class="logo-wrapper">
    <img src="img/logo.png" class="logo">
  </div>
  <nav id="my-menu">
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a>
         <ul class="Vertical">
            <li><a href="#">What we offer</a></li>
              <li><a href="#"><dir>Bodybuilding exercises</dir></a></li>
              <li><a href="#"><dir>Bodybuilding nutrition</dir></a></li>
              <li><a href="#"><dir>Training packages</dir></a></li>
              <li><a href="#"><dir>Gym equipment</dir></a></li>
            <li><a href="#">Benefits</a></li>
            <li><a href="#">Our programs</a></li>
            <li><a href="#">Testimonials</a></li>
         </ul>
      </li>
      <li><a href="#">Services</a></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Gallery</a></li>
      <li><a href="#">Contacts</a></li>
    </ul>
  </nav>
</div>

<div id="header-desktop">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="logo">
          <img src="img/logo2.png" class="img-responsive">
        </div>
      </div>
      <div class="col-xs-1">
        <a href="#" class="home">HOME</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="about">ABOUT</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="services">SERVICES</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="news">NEWS</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="gallery">GALLERY</a>
      </div>
      <div class="col-xs-1">
        <a href="#" class="contacts">CONTACTS</a>
      </div>
    </div>
  </div>
</div>
