<div id="form">
  <div class="title ">
    <h1>CONTACT US</h1>
  </div>
  <div class="line">
    <h2>_____</h2>
  </div>
  <div class="icons">
    <div class="ihouse">
      <i class="fas fa-house-damage"></i>
      <p>9863 - 9867 Mill Road, Cambridge MG09 99HT</p>
    </div>
    <div class="ipaper">
      <i class="fas fa-house-damage"></i>
      <p>+1 800 603 6035</p>
    </div>
    <div class="imail">
      <i class="far fa-envelope"></i>
      <p>mail@demolink.org</p>
    </div>
  </div>
  <div class="formu">
    <form action="registrodedatos.php" method="post">
      <div class="inputs">
        <input type="text" name="name" value="Name*">
        <input type="text" name="mail" value="E-mail*">
        <input type ="text" name="phone" value="Phone*">
      </div>
      <div class="botton">
        <input type="submit" name="send" value="Send">
      </div>
    </form>
</div>
