<div id="form" class="container">
  <div class="wrapper-form">
    <div class="title">
      <h1>CONTACT US</h1>
    </div>
    <div class="line">
      -------
    </div>
    <div class="icons text-center">
      <div class="ihouse col-sm-4">
        <span><i class="fas fa-house-damage"></i></span>
        <p>9863 - 9867 Mill Road, Cambridge MG09 99HT</p>
      </div>
      <div class="ipaper col-sm-4">
        <span><i class="far fa-paper-plane"></i></span>
        <p>+1 800 603 6035</p>
      </div>
      <div class="imail col-sm-4">
        <span><i class="far fa-envelope"></i></span>
        <p>mail@demolink.org</p>
      </div>
    </div>
  <div class="formu">
    <div class="row">
      <div class="wrapper-formu text-center">
        <form action="registrodedatos.php" method="post">
          <div class="inputs">
            <div class="row">
              <input type="text" class="circle" name="name" value="Name*">
              <input type="text" class="circle" name="mail" value="E-mail*">
              <input type ="text" class="circle" name="phone" value="Phone*">
              <div class="wrapper-message">
                <textarea cols="25" rows="20" class="circle hidden-1">Message*</textarea>
              </div>
              <div class="wrapper-message">
                <textarea cols="95" rows="15" class="circle hidden-2">Message*</textarea>
              </div>
              <div class="wrapper-message">
                <textarea cols="130" rows="13" class="circle hidden-3">Message*</textarea>
              </div>
            </div>
          </div>
          <div class="botton">
            <input type="submit" class="send" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</div>
