<div id="latest-news" class="container-fluid">
  <h1>LATEST NEWS</h1>
  <div class="line"></div>
  <div class="row">
    <div class="col-sm-4">
      <div class="inner">
        <img src="../../img/img-1.jpg" class="img-responsive">
        <a href="#">Training seminar</a>
        <p>Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipis cing elit. Mauris fermentum ictum magna. Sed laoreet aliquam leo. Ut tellus dolor, pibus eget, elementum vel, cursus eleifend, elit.</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="inner">
        <img src="../../img/img-2.jpg"class="img-responsive">
        <a href="#">plants build muscle</a>
        <p>Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipis cing elit. Mauris fermentum ictum magna. Sed laoreet aliquam leo. Ut tellus dolor, pibus eget, elementum vel, cursus eleifend, elit.</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="inner">
        <img src="../../img/img-3.jpg" class="img-responsive">
        <a href="#">Aenean auctor wisi et urna erat</a>
        <p>Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipis cing elit. Mauris fermentum ictum magna. Sed laoreet aliquam leo. Ut tellus dolor, pibus eget, elementum vel, cursus eleifend, elit.</p>
      </div>
    </div>
  </div>
</div>
