<div id="fresh-news">
  <h1>FRESH NEWS</h1>
  <div class="line"></div>
  <div class="row">
    <div class="col">
      <div class="date">26 May, 2015</div>
      <div class="title">Tim Pool became the best in the bodybuilders competition</div>
      <div class="text">Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada.</div>
    </div>
    <div class="col">
      <div class="date">17 June, 2015</div>
      <div class="title">Performance of women's bodybuilders team</div>
      <div class="text">Cum sociis natoque penatibus et magnis dis partu rient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus.</div>
    </div>
  </div>
  <div class="button">
    <button type="button" class="btn btn-primary">Read More</button>
</div>

