<div id="training-packages">
  <div class="title">NEW TRAINING PACKAGES</div>
  <div class="line"></div>
  <div class="row">
    <div class="col-sm-3">
      <div class="numbers">01</div>
      <div class="title2">Personal training</div>
      <div class="text">Our certified work trainers are dedicated to provide requisite guidance through your customized fitness regimes that suite your body type.</div>
    </div>
    <div class="col-sm-3">
      <div class="numbers">02</div>
      <div class="title2">Aerobic group exercises</div>
      <div class="text">Our experienced trainers through the rhythmic aerobics exercises not only fulfill your desire of a toned body, but also give a fun and healthy start for your day.</div>
    </div>
    <div class="col-sm-3">
      <div class="numbers">03</div>
      <div class="title2">Weight gain program</div>
      <div class="text">If you believe you are underweight, too thin or need more muscle then we have a variety of weight gaining programs.</div>
    </div>
    <div class="col-sm-3">
      <div class="numbers">04</div>
      <div class="title2">Weight loss program</div>
      <div class="text">With the help and guidance of our expert team of Trainers and Dietician, we provide diet counseling sessions to all our customers.</div>
    </div>
</div>
  <div class="button">
    <button type="button" class="btn btn-primary">Read More</button>
</div>