<div id="news-center">
  <div class="row">
    <div class="col-sm-6 columna1">
        <div class="title3">NEWS CENTER</div>
        <div class="line2"></div>
        <div class="subtitle">Opening of a new sports hall for bodybuilders</div>
        <div class="text1">Cum sociis natoque penatibus magnis dis parturient montes, nascetur ridiculus mus. Nulla dusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem bus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at.</div>
        <div class="button">
          <button type="button" class="btn btn-primary">Read More</button>
        </div>
    </div>
</div>
