<div id="our-programs">
  <div class="container">
    <div class="box">
      <div class="row">

        <div class="col-12">
          <div class="title">
          <h1>OUR PROGRAMS</h1>
          </div>
          <div class="line"></div>
        </div>

        <div class="col-12 col-md-5">
          <div class="title">
            <h3>Our programs can help you become stronger and
            healthier</h3>
          </div>
          <div class="body">
            <p class="text-justify-left">
            For anyone looking to pack on some serious muscle mass,
            one of the top priorities will be to determine what the best
            bodybuilding workout to follow. There is a wide range of different
            workouts available, so choosing the one that will suit your needs
            best is important. It's also essential that you understand which
            factors contribute the most to gaining lean muscle mass.
            A program that utilizes these principles will often fare
            better than one that doesn't.
            </p>
          </div>
        </div>
      </div>
      <div class="row">
         <div class="col-12">
          <div class="text-left cta">
            <a href="#">Read More</a>
          </div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>
