<div id="what-clients-say">
  <div class="container">
    <div class="row">

      <div class="col-12">
        <div class="text-center title">
          <h1>WHAT CLIENTS SAY</h1>
        </div>
        <div class="line"></div>
      </div>

      <div class="col-12 col-sm-6">
        <div class="testimonials">
          <p>I began bodybuilding at the age of 41, on a dare from one of my gym buddies. My body became sculpted, hard and vascular. When I stepped out on stage for the first time, I was competing with 13 other guys that were half my age and I won the Novice class!<br><br>Tom Piston</p>
        </div>
      </div>

      <div class="col-12 col-sm-6">
        <div class="testimonials">
          <p>I’ve trained at many gyms. The place inspires potential and gets results. What’s helped my progress rapidly is the wealth of knowledge in the gym, amongst staff and other fellow members. It feels great to train in a friendly environment, amongst champions.<br><br>Sam Kromstain</p>
        </div>
      </div>

    </div>
  </div>
</div>
