<div id="our-benefits">
  <div class="container">
    <div class="row">

      <div class="col-12">
        <div class="title text-center">
          <h1>OUR BENEFITS</h1>
        </div>
        <div class="line"></div>
      </div>

      <div class="con col-12 col-sm-4">
        <div class="title">
          <h4>Increase of muscular strength</h4>
        </div>
        <div class="body">
          <p class="text-justify">Body building can increase the muscular strength of a person.
          The strength of a person is very important in everyday living like lifting objects
          and transferring them to other places.Body building does not only increase muscular
          strength but as well as the bone and ligament strength.</p>
        </div>
      </div>

      <div class="con col-12 col-sm-4">
        <div class="title">
          <h4>Fexibility of the body</h4>
        </div>
        <div class="body">
          <p class="text-justify">Though exposed to great stresses and strains, body building can add flexibility
          to the body. Body building can be improved since discipline is always to be observed.
          Right food and at the same time right routines of exercise can help
          improve physical and health fitness.</p>
        </div>
      </div>

      <div class="con col-12 col-sm-4">
        <div class="title">
          <h4>Beauty and health</h4>
        </div>
        <div class="body">
          <p class="text-justify text-center">Body building can make the heart healthier.
           When a person exerts more effort or consumes energy,
          heart is exercised through the heart beats.
          When done constantly, the hearts muscles are strengthened.
          When doing routines or exercising, voluminous fats are burned.</p>
         </div>
      </div>
    </div>

        <div class="text-center cta">
          <a href="">Read More</a>
        </div>
  </div>
</div>