<div class="section-2">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <h1>WHAT WE OFFER </h1>
        <div class="line"></div>
        <div class="item col col-md-2">
         <span class="icon heart"></span>
         <h4>Bodybuilding exercises</h4>
         <p>For each muscle group there exist many different exercises. It is very important to realize that not all of those exercises are equally suitable for stimulation your muscles to grow.</p>
        </div>
        <div class="item col col-md-2">
          <span class="icon lock"></span>
          <h4>Bodybuilding nutrition</h4>
          <p>Nutrition is extremely important in bodybuilding, but fortunately it is also very simple. Basically a good bodybuilding diet equals a normal healthy diet plus three big protein shakes per day.</p>
        </div>
        <div class=" item col col-md-2">
          <span class="icon user"></span>
          <h4>Training packages</h4>
          <p>Training is by far the most complicated and important aspect of true natural bodybuilding. If you are new to bodybuilding, our coaches will help you write a program just for you.</p>
        </div>
        <div class="item col col-md-2">
          <span class="icon clock"></span>
          <h4>Gym equipment</h4>
          <p>It is very important to have high q uality equipment available so that you can perform your exercises correctly and get the results that you deserve.</p>
        </div>
      </div>
    </div>
    <div col="col-2 text-center">
      <div class="col-2 cta-2 ">
        <a href="#">Read More</a>
      </div>
    </div>
   </div>
  </div>
</div>
