<div id="our-benefits">

  <div class="container-fluid">
    <div class="row">

      <div class="col-12">
        <h1>OUR BENEFITS</h1>
        <p></p>
      </div>

      <div class="col-12 col-sm-4">
        <h3>Increase of muscular strength</h3>
        <p></p>
      </div>

      <div class="col-12 col-sm-4">
        <h3>Flexibility of the body</h3>
      </div>

      <div class="col-12 col-sm-4">
        <h3>Beauty and health</h3>
        <p></p>
      </div>

      <div class="col-12">
        <a href="">Read More</a>
      </div>

    </div>
  </div>
</div>