<div class="section-1">
  <div class="container">
    <div class="row">
      <div class="col col-md-6 col-md-offset-6">
        <div id="body">
          <h1>ABOUT US</h1>
           <div class="line"></div>
          <h5>bodybuilding takes a lot of hard work and dedication</h5>
          <p>In the modern bodybuilding industry, "professional" generally means a bodybuilder who has won qualifying competitions as an amateur and has earned a "pro card" from their respective organization. Professionals earn the right to compete in competitions that include monetary prizes. Depending on the level of success, these bodybuilders may receive monetary compensation from sponsors, much like athletes in other sports.
          </p>
        </div>
        <div class="cta-1 col-md-2 text-center">
          <a href="#">Read More</a>
        </div>
      </div>
    </div>
  </div>
</div>
